### ISSUE TITLE
Saving recording

### ISSUE THREAD

**Issue by jbmelander** [flatironinstitute/mountainsort5#12]
I am using a dataset with 100 channels that lasts ~1.5 hours and wanted to share the following observation.

1. Using scheme2 with lazy loading, the sorting took ~194 minutes.
2. Leaving all parameters the same, I first saved the recording in binary format and used the loaded binary recording object. With this, sorting took ~14 minutes.

It might be good to include this in the README - as it seems to be a significant speed-boost for large datasets.

**Comment by magland** [comment]
Wow that's a huge difference. What was the format of the data that you were lazy loading?

**Comment by jbmelander** [comment]
SpikeGLX binary files

**Comment by magland** [comment]
I haven't worked with that format. We'll have to get this sorted out...
