### ISSUE TITLE
Does the signal need to be inverted before running mountainsort5?

### ISSUE THREAD

**Issue by dejanica93** [flatironinstitute/mountainsort5#29]
Hello,

I just wanted to check if the signal should be inverted or does that not matter?

Best,
Dejana

**Comment by magland** [comment]
Hi Dejana,
There is a detect_sign parameter that can be set to -1, 1, or 0 which determines whether the algorithm looks for positive, negative, or both spikes.
https://github.com/flatironinstitute/mountainsort5/blob/main/docs/scheme1.md#parameters
Jeremy

**Comment by dejanica93** [comment]
Great! Thank you!
