### ISSUE TITLE
threshold

### ISSUE THREAD

**Issue by Hanlin-Zhu** [flatironinstitute/mountainsort5#4]
Hi Dr.Margland, 
      I noticed that you suggested 5.5sd for ms5 for spike detection, do you suggest changing the threshold of the previous version ms4 to 5.5 as well or this behavior is specific to ms5? Separately do you kindly have any insight on how might the recording duration change this parameter?   Thanks.

**Comment by magland** [comment]
Hi,
No, this suggestion does not apply to ms4.
I am not totally confident in that choice even though it says that in the docs -- for one dataset I am using 4.5 to capture more low-amp events.
Duration should not affect this.

**Comment by Hanlin-Zhu** [comment]
Thank you!
