### ISSUE TITLE
Slow computation of pca features

### ISSUE THREAD

**Issue by chrishalcrow** [flatironinstitute/mountainsort5#50]
Hello,

We’ve been using mountainsort5 recently (whose results we love!), but are having a problems applying it to full, hour-long NP2 recordings. The killer, time-wise, seems to be the “Computing PCA features with npca=…” during the initial steps.

Here’s the timings as we increase channel number. The number of pcas computed and the spikes detected scale (basically) linearly with channel number.

| Num channels  | Time taken to do `compute pca` step |
| ------------- | ------------- |
| 100  | 391.5 |
| 150  | 1013.7 |
| 200 | 3685.7 |

I’m running the 384 channel recording, and have been waiting 24 hours. Is it expected that this step should take so long? Or do you have any tips on how to speed up this step that I'm missing?

Here’s the code used to generate those timings:

``` python
si.set_global_job_kwargs(n_jobs=8)
channels = 20

recording = ...
recording_filtered = si.whiten(si.bandpass_filter(recording, freq_min=300, freq_max=6000, dtype=np.float32))
recording_filtered = recording_filtered.channel_slice(channel_ids=recording.channel_ids[:channels])


recording_saved = recording_filtered.save_to_folder(folder=cohort_folder+f"derivatives/temp_ms_{channels}",overwrite=True)

sorting = ms.sorting_scheme2(
    recording=recording_saved,
    sorting_parameters=ms.Scheme2SortingParameters(
                phase1_detect_channel_radius=150,
                detect_channel_radius=50,
                training_duration_sec=60
            )
)
```

**Comment by jbmelander** [comment]
I can share the current script I use for neuropixel 2.0 recordings. Ill make a PR later today.

Off the bat, I think setting n_jobs to -1 could make a big difference.

On Dec 16, 2024 6:36 AM, Chris Halcrow ***@***.***> wrote:

Hello,

We’ve been using mountainsort5 recently (whose results we love!), but are having a problems applying it to full, hour-long NP2 recordings. The killer, time-wise, seems to be the “Computing PCA features with npca=…” during the initial steps.

Here’s the timings as we increase channel number. The number of pcas computed and the spikes detected scale (basically) linearly with channel number.

Num channels    Time taken to do compute pca step
100     391.5
150     1013.7
200     3685.7

I’m running the 384 channel recording, and have been waiting 24 hours. Is it expected that this step should take so long? Or do you have any tips on how to speed up this step that I'm missing?

Here’s the code used to generate those timings:

si.set_global_job_kwargs(n_jobs=8)
channels = 20

recording = ...
recording_filtered = si.whiten(si.bandpass_filter(recording, freq_min=300, freq_max=6000, dtype=np.float32))
recording_filtered = recording_filtered.channel_slice(channel_ids=recording.channel_ids[:channels])


recording_saved = recording_filtered.save_to_folder(folder=cohort_folder+f"derivatives/temp_ms_{channels}",overwrite=True)

sorting = ms.sorting_scheme2(
    recording=recording_saved,
    sorting_parameters=ms.Scheme2SortingParameters(
                phase1_detect_channel_radius=150,
                detect_channel_radius=50,
                training_duration_sec=60
            )
)

**Comment by chrishalcrow** [comment]
Thanks both for the replies!

The slow line is
https://github.com/flatironinstitute/mountainsort5/blob/111825a829e6c489e29c2a368b85c168b31fc6a7/mountainsort5/core/compute_pca_features.py#L28
which I guess makes sense. This is not parallelised so more cores aren't going to help.

I wonder if there's a faster implementation of `fit_transform` (which is just a `fit` then a `transform`) somewhere else. 

I'll try running with a more aggressive threshold value - thanks for the idea

Just to check that I've understood the code correctly, mountainsort:
- Takes a a "training" slice of the recording
- Extracts snippets from the training data. There are `num_of_spikes` snippets and each is `samples`x`channels` sized
- Computes pcas for all snippets on all channels

So other ways to speed this up is to have a shorter recording time or reduce the number of pca components computed per snippet?

**Comment by jbmelander** [comment]
I'll just mention that, because of what you point out, specifying more jobs can actually hurt you - and the -1 is in my experience the most efficient when using spikeinterface to run the sorter



________________________________

**Comment by magland** [comment]
Yeah I would expect there to be a much faster way to do the pca. And really it only needs to be an approximate pca. If you come across anything, let me know.

> Just to check that I've understood the code correctly, mountainsort:
> Takes a a "training" slice of the recording
> Extracts snippets from the training data. There are num_of_spikes snippets and each is samplesxchannels sized
> Computes pcas for all snippets on all channels

Yes I believe that's right.

> So other ways to speed this up is to have a shorter recording time or reduce the number of pca components computed per snippet?

Yeah. Or decrease the number of time samples per snippet I suppose.

**Comment by chrishalcrow** [comment]
Ok, great! I'll play and benchmark, and ask some smarter-than-I-am friends about an alternative to `fit_transform`. Thanks!

**Comment by jbmelander** [comment]
I'll give you a ping when I have the new script pushed - it works for me with 2.0 recordings pretty well.



________________________________
