### ISSUE TITLE
Parameters list for compatibility for spikeinterface

### ISSUE THREAD

**Issue by carlacodes** [flatironinstitute/mountainsort5#7]
Hi, is there a list of spike sorting parameters in the code somewhere that I can directly reference in my spikeinterface jobs? Reading the documentation, the parameters are organised into sorting schemes, but I would like to know if I can extract the actual parameters corresponding to these schemes. Right now, I only have two parameters implemented (filter, whiten) in my json file which seems to work fine: 
```
    "sorter_params":
    {
        "mountainsort5":
        {
            "filter": false,
            "whiten": false
        }
    },
```

However, I can't easily find the full list of adjustable parameters within the source code.

 For instance, I'd like to know if there is a parameter to handle multiple cores (in ms4 I believe it was num_workers, but I can't find something similar in ms5).

Otherwise, ms5 seems to be much faster than ms4, which is very exciting.
Many thanks for your time.

**Comment by carlacodes** [comment]
As a follow-up, are these all of the available modifiable parameters in ms5 (class Scheme2SortingParameters)?:[https://github.com/flatironinstitute/mountainsort5/blob/3e8507683a11bc92472d01932ee0b6f43587047a/mountainsort5/schemes/Scheme2SortingParameters.py#L8](https://github.com/flatironinstitute/mountainsort5/blob/3e8507683a11bc92472d01932ee0b6f43587047a/mountainsort5/schemes/Scheme2SortingParameters.py#L8)

**Comment by magland** [comment]
Yes.

See here for the list of ms5 parameters in spikeinterface

https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/sorters/external/mountainsort5.py

BTW, it's very important to do filter and whiten in ms5

**Comment by carlacodes** [comment]
Great, thanks; yes, I do filtering and whitening as a separate pre-processing step. Closing this thread now.
