### ISSUE TITLE
Confusion about actual # PC's used in SnippetClassifier

### ISSUE THREAD

**Issue by oaaij-gnahz** [flatironinstitute/mountainsort5#9]
Hi, while learning about Mountainsort5, I am confused about the number of PC's used in `SnippetClassifier` in scheme 2. 

The scheme 2 [doc](https://github.com/flatironinstitute/mountainsort5/blob/main/docs/scheme2.md) describes `classifier_npca` as follows:

The number of principal components to use for each neighborhood classifier. If None (the default), then the number of principal components will be automatically determined as min(12, M * 3) where M is the number of channels in the neighborhood.

Whereas [SnippetClassifier,fit()](https://github.com/flatironinstitute/mountainsort5/blob/main/mountainsort5/core/SnippetClassifier.py#L28) reads:

```
            effective_npca = max(12, self.M * 3)
```

So shall the algorithm use not more than or not less than 12 PC's for classification?

Thanks!

**Comment by magland** [comment]
@oaaij-gnahz Thanks so much for the report, that was indeed an error in the doc. I have updated it to `max`
